name: Node.js Package

on:
  push:
    tags:
      - 'v*'  # Publikuj przy każdym tagu zaczynającym się od 'v'

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Set up NPM token
        run: echo "//registry.npmjs.org/:_authToken=${{ secrets.NPM_TOKEN }}" > ~/.npmrc

      - name: Install dependencies
        run: npm install

      - name: Publish package
        run: npm publish